confluence:
  base_url: ${BASE_URL}
  space_key: ${SPACE_KEY}
  pat: ${PAT}

mongo:
  uri: ${MONGO_URI}
  db: ${MONGO_DB}
  collection: pages

qdrant:
  url: ${QDRANT_URL}
  collection: confluence_vectors_fastembed

llm:
  base_url: "http://localhost:1234/v1"
  model: "openai/gpt-oss-20b"
  embedding_model: "BAAI/bge-small-en-v1.5" # FastEmbed default
  rerank_model: "ms-marco-TinyBERT-L-2-v2" # FlashRank default

params:
  chunk_size: 500
  overlap: 100
  top_k: 5
